defaults: &defaults
  version: 873
  # use local file as default
  #wsdl_file: 'http://developer.ebay.com/webservices/873/eBaySvc.wsdl'
  routing: default
  siteid: 0
  preload: false
  warning_level: Low
  error_language: en_US
  api_keys: []
  savon_log_level: debug
  sandbox_url: 'https://api.sandbox.ebay.com/wsapi'
  live_url: 'https://api.ebay.com/wsapi'

development: &development
  <<: *defaults
  warning_level: High
  savon_log_level: info

test:
  <<: *development

production:
  <<: *defaults
  preload: true
